### ISSUE TITLE
[BUG] Error executing native

### ISSUE THREAD

**Issue by divide29** [qbcore-framework/qb-target#162]
**Describe the bug**
![image](https://user-images.githubusercontent.com/92187331/192162120-f3a468d5-5a49-4257-ac00-bdb028d2da6b.png)

**To Reproduce**
Just spawn.

**Comment by rpxyz** [comment]
I have the exact same error, was coming here to report it but as its done then I will just say your not the only one. :)

**Comment by DannyHD001** [comment]
Just jumping in to say I also got this error now. Not sure what caused it as it shows everytime I press LEFT ALT

**Comment by jimgordon20** [comment]
still not fix ?

**Comment by KingRyuShin** [comment]
@divide29 @rxnm @DannyHD001 @jimgordon20 
You guys get that error because you are not loading Qb-Target correctly.. it should be loaded before any script that call qb-target.. so in your server.cfg you need to place Qb-Target like this : 

```
# QBCore & Extra stuff
ensure oxmysql
ensure qb-core
ensure qb-target
ensure [qb]
ensure [standalone]
ensure [voice]
```

Otherwise you will get a native error when you are using the eye and not targeting anything !
Have fun :)
